# -*- coding: utf-8 -*-
"""Introduction to Tensorflow for AI, ML and DS_Hello world code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OZs8PgiQKTJ8lx56o_Qya5ccRdEDcXb-
"""

import numpy as np
import tensorflow as tf

"""Dense means one layer and 
units = 1 means one neuron

Sequential means layers are used in sequence one after the other.
"""

model = tf.keras.Sequential([
        tf.keras.layers.Dense(units = 1, input_shape = [1])                     
])

model.compile(
    loss = tf.keras.losses.MAE,
    optimizer = tf.keras.optimizers.SGD(),
    metrics = ['mse']
)

X = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0])
y = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0])

model.fit(X, y, epochs = 500, verbose = 0)

"""during each epoch what happens is, our model guess a relation/patter between X and y, then the loss function is used to check how wrong the guess is with the ground truth/actual value, then optimizer improves the guess. This is called one epoch.

Lower loss function means the model is closer to find the relation between X and y.
"""

y_pred = model.predict([10])
y_pred

